version: "3"
services:
  db:
    image: postgres:latest
    networks:
      - hmpps
    container_name: book-a-video-link-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: book-a-video-link-db
      POSTGRES_USER: book-a-video-link
      POSTGRES_PASSWORD: book-a-video-link
    volumes:
      - ./docker-init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  hmpps: