version: "3"
services:
  db:
    image: postgres:latest
    networks:
      - hmpps
    container_name: book-a-video-link-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: book-a-video-link-db
      POSTGRES_USER: book-a-video-link
      POSTGRES_PASSWORD: book-a-video-link
    volumes:
      - ./docker-init.sql:/docker-entrypoint-initdb.d/init.sql

  local-stack-aws:
    image: localstack/localstack:3
    networks:
      - hmpps
    container_name: local-sqs
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns,sqs
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"

networks:
  hmpps:
