-- =============================================
-- Base data
-- =============================================

insert into reference_code (reference_code_id, group_code, code, description,created_by, created_time)
values ( 1, 'COURT_HEARING_TYPE', 'APPEAL', 'Appeal', 'TIM', current_timestamp),
       ( 2, 'COURT_HEARING_TYPE', 'APPLICATION', 'Application', 'TIM', current_timestamp),
       ( 3, 'COURT_HEARING_TYPE', 'BACKER',  'Backer trial', 'TIM', current_timestamp),
       ( 4, 'COURT_HEARING_TYPE', 'BAIL', 'Bail', 'TIM', current_timestamp),
       ( 5, 'COURT_HEARING_TYPE', 'CIVIL', 'Civil', 'TIM', current_timestamp),
       ( 6, 'COURT_HEARING_TYPE', 'CSE', 'Committal for sentence (CSE)','TIM', current_timestamp),
       ( 7, 'COURT_HEARING_TYPE', 'CTA', 'Custody time limit application (CTA)', 'TIM', current_timestamp),
       ( 8, 'COURT_HEARING_TYPE', 'IMMIGRATION_DEPORTATION', 'Immigration/deportation', 'TIM', current_timestamp),
       ( 9, 'COURT_HEARING_TYPE', 'FAMILY', 'Family', 'TIM', current_timestamp),
       (10, 'COURT_HEARING_TYPE', 'TRIAL', 'Trial', 'TIM', current_timestamp),
       (11, 'COURT_HEARING_TYPE', 'FCMH', 'Further case management hearing (FCMH)', 'TIM', current_timestamp),
       (12, 'COURT_HEARING_TYPE', 'FTR', 'Future trial review hearing (FTR)', 'TIM', current_timestamp),
       (13, 'COURT_HEARING_TYPE', 'GRH', 'Ground rules hearing (GRH)', 'TIM', current_timestamp),
       (14, 'COURT_HEARING_TYPE', 'MDA', 'Mention hearing (MDA)', 'TIM', current_timestamp),
       (15, 'COURT_HEARING_TYPE', 'MEF', 'Mention to fix (MEF)', 'TIM', current_timestamp),
       (16, 'COURT_HEARING_TYPE', 'NEWTON', 'Newton hearing', 'TIM', current_timestamp),
       (17, 'COURT_HEARING_TYPE', 'PLE', 'Plea hearing (PLE)', 'TIM', current_timestamp),
       (18, 'COURT_HEARING_TYPE', 'PTPH', 'Plea trial and preparation hearing (PTPH)', 'TIM', current_timestamp),
       (19, 'COURT_HEARING_TYPE', 'PTR', 'Pre-trial review (PTR)', 'TIM', current_timestamp),
       (20, 'COURT_HEARING_TYPE', 'POCA', 'Proceeds of crime application (POCA)', 'TIM', current_timestamp),
       (21, 'COURT_HEARING_TYPE', 'REMAND', 'Remand hearing', 'TIM', current_timestamp),
       (22, 'COURT_HEARING_TYPE', 'SECTION_28', 'Section 28', 'TIM', current_timestamp),
       (23, 'COURT_HEARING_TYPE', 'SEN', 'Sentence (SEN)', 'TIM', current_timestamp),
       (24, 'COURT_HEARING_TYPE', 'TRIBUNAL', 'Tribunal', 'TIM', current_timestamp),
       (25, 'COURT_HEARING_TYPE', 'OTHER', 'Other', 'TIM', current_timestamp),
       (26, 'PROBATION_MEETING_TYPE', 'PSR', 'Pre-sentence report', 'TIM', current_timestamp),
       (27, 'PROBATION_MEETING_TYPE', 'RR', 'Recall report', 'TIM', current_timestamp),
       (28, 'BOOKING_TYPE', 'COURT', 'Court hearing', 'TIM', current_timestamp),
       (29, 'BOOKING_TYPE', 'PROBATION', 'Probation meeting', 'TIM', current_timestamp),
       (30, 'STATUS_CODE', 'ACTIVE', 'Active', 'TIM', current_timestamp),
       (31, 'STATUS_CODE', 'EXPIRED', 'Expired', 'TIM', current_timestamp),
       (32, 'STATUS_CODE', 'CANCELLED', 'Cancelled', 'TIM', current_timestamp),
       (33, 'THIRD_PARTY_TYPE', 'INTERPRETER', 'Interpreter', 'TIM', current_timestamp),
       (34, 'THIRD_PARTY_TYPE', 'LEGAL', 'Legal representative', 'TIM', current_timestamp),
       (35, 'THIRD_PARTY_TYPE', 'PROBATION_OFFICER', 'Probation officer', 'TIM', current_timestamp),
       (36, 'THIRD_PARTY_TYPE', 'OTHER_PARTY', 'Other third party', 'TIM', current_timestamp),
       (37, 'APPOINTMENT_TYPE', 'VLB_COURT_PRE', 'Video link booking - pre conference', 'TIM', current_timestamp),
       (38, 'APPOINTMENT_TYPE', 'VLB_COURT_MAIN', 'Video link booking - hearing', 'TIM', current_timestamp),
       (39, 'APPOINTMENT_TYPE', 'VLB_COURT_POST', 'Video link booking - post conference', 'TIM', current_timestamp),
       (40, 'APPOINTMENT_TYPE', 'VLB_PROBATION', 'Video link booking - probation', 'TIM', current_timestamp),
       (41, 'EXTERNAL_SYSTEM', 'AA', 'Activities and appointments', 'TIM', current_timestamp),
       (42, 'EXTERNAL_SYSTEM', 'NOMIS', 'NOMIS', 'TIM', current_timestamp),
       (43, 'NOTIFY_REASON', 'NOTIFY_3RD_PARTY', 'Notify third party', 'TIM', current_timestamp),
       (44, 'NOTIFY_REASON', 'NOTIFY_COURT', 'Notify court contact', 'TIM', current_timestamp),
       (45, 'NOTIFY_REASON', 'NOTIFY_PROBATION', 'Notify probation contact', 'TIM', current_timestamp),
       (46, 'NOTIFY_REASON', 'NOTIFY_PRISON', 'Notify prison contact', 'TIM', current_timestamp),
       (47, 'NOTIFY_REASON', 'NOTIFY_USER', 'Notify user', 'TIM', current_timestamp),
       (48, 'HISTORY_TYPE', 'HIST_CREATED', 'Created', 'TIM', current_timestamp),
       (49, 'HISTORY_TYPE', 'HIST_AMENDED', 'Amended', 'TIM', current_timestamp),
       (50, 'HISTORY_TYPE', 'HIST_CANCELLED', 'Cancelled', 'TIM', current_timestamp);

alter sequence if exists reference_code_reference_code_id_seq restart with 51;

---

insert into court (court_id, code, description, enabled, notes, created_by, created_time)
values (1, 'DRBYMC', 'Derby Justice Centre', true, null, 'TIM', current_timestamp),
(2, 'NWPIAC', 'IAC Newport', true, null, 'TIM', current_timestamp),
(3, 'CRNRCT', 'Caernarfon County', true, null, 'TIM', current_timestamp),
(4, 'CRNRCC', 'Caernarfon Crown', true, null, 'TIM', current_timestamp),
(5, 'CRNHMC', 'Caernarfon Magistrates', true, null, 'TIM', current_timestamp),
(6, 'CHSTMC', 'Chesterfield Justice Centre', true, null, 'TIM', current_timestamp),
(7, 'CVNTCC', 'Coventry Crown', true, null, 'TIM', current_timestamp),
(8, 'CVNTMC', 'Coventry Magistrates', true, null, 'TIM', current_timestamp),
(9, 'CRT034', 'Westminster Magistrates', true, null, 'TIM', current_timestamp),
(10, 'CRYDMC', 'Croydon Magistrates', true, null, 'TIM', current_timestamp),
(11, 'DRBYCC', 'Derby Crown', true, null, 'TIM', current_timestamp),
(12, 'HERFMC', 'Hereford Magistrates', true, null, 'TIM', current_timestamp),
(13, 'MNSFMC', 'Mansfield Justice Centre', true, null, 'TIM', current_timestamp),
(14, 'MOLDCT', 'Mold County', true, null, 'TIM', current_timestamp),
(15, 'MOLDCC', 'Mold Crown', true, null, 'TIM', current_timestamp),
(16, 'MOLDMC', 'Mold Magistrates', true, null, 'TIM', current_timestamp),
(17, 'NOTTCC', 'Nottingham Crown', true, null, 'TIM', current_timestamp),
(18, 'NOTTMC', 'Nottingham Justice Centre', true, null, 'TIM', current_timestamp),
(19, 'PRSTMC', 'Prestatyn County', true, null, 'TIM', current_timestamp),
(20, 'SHRWCC', 'Shrewsbury Crown', true, null, 'TIM', current_timestamp),
(21, 'SEVNMC', 'Sevenoaks Magistrates', true, null, 'TIM', current_timestamp),
(22, 'OXFDCC', 'Oxford Crown', true, null, 'TIM', current_timestamp),
(23, 'OXFRMC', 'Oxfordshire Magistrates', true, null, 'TIM', current_timestamp),
(24, 'READCC', 'Reading Crown', true, null, 'TIM', current_timestamp),
(25, 'READMC', 'Reading Magistrates', true, null, 'TIM', current_timestamp),
(26, 'SLOUMC', 'Slough Magistrates', true, null, 'TIM', current_timestamp),
(27, 'SWINCC', 'Swindon Crown', true, null, 'TIM', current_timestamp),
(28, 'SWINMC', 'Swindon Magistrates', true, null, 'TIM', current_timestamp),
(29, 'AMERCC', 'Amersham Crown', true, null, 'TIM', current_timestamp),
(30, 'AYLSCC', 'Aylesbury Crown', true, null, 'TIM', current_timestamp),
(31, 'WYCBMC', 'High Wycombe Magistrates', true, null, 'TIM', current_timestamp),
(32, 'MLTKMC', 'Milton Keynes Magistrates', true, null, 'TIM', current_timestamp),
(33, 'CAMBCT', 'Cambridge Crown', true, null, 'TIM', current_timestamp),
(34, 'CAMBMC', 'Cambridge Magistrates', true, null, 'TIM', current_timestamp),
(35, 'HUNTMC', 'Huntingdon Law Courts', true, null, 'TIM', current_timestamp),
(36, 'PBORCC', 'Peterborough Crown', true, null, 'TIM', current_timestamp),
(37, 'NRTHCC', 'Northampton Crown', true, null, 'TIM', current_timestamp),
(38, 'NRTHMC', 'Northampton Magistrates', true, null, 'TIM', current_timestamp),
(39, 'WELBMC', 'Wellingborough Justice Centre', true, null, 'TIM', current_timestamp),
(40, 'BRMNCC', 'Birmingham Crown', true, null, 'TIM', current_timestamp),
(41, 'BRMCMC', 'Birmingham Magistrates', true, null, 'TIM', current_timestamp),
(42, 'BROMMC', 'Bromley Magistrates', true, null, 'TIM', current_timestamp),
(43, 'CHELMC', 'Cheltenham Magistrates', true, null, 'TIM', current_timestamp),
(44, 'CITYMC', 'City of London Magistrates', true, null, 'TIM', current_timestamp),
(45, 'DUDLMC', 'Dudley Magistrates', true, null, 'TIM', current_timestamp),
(46, 'INNRCC', 'Inner London Crown', true, null, 'TIM', current_timestamp),
(47, 'KIDDMC', 'Kidderminster Magistrates', true, null, 'TIM', current_timestamp),
(48, 'KNGTCC', 'Kingston upon Thames Crown', true, null, 'TIM', current_timestamp),
(49, 'LEAMMC', 'Leamington Spa Magistrates', true, null, 'TIM', current_timestamp),
(50, 'RDDTMC', 'Redditch Magistrates', true, null, 'TIM', current_timestamp),
(51, 'TELFMC', 'Telford Magistrates', true, null, 'TIM', current_timestamp),
(52, 'WRWKCC', 'Warwick Crown', true, null, 'TIM', current_timestamp),
(53, 'WMBLMC', 'Wimbledon Magistrates', true, null, 'TIM', current_timestamp),
(54, 'STHWCC', 'Southwark Crown', true, null, 'TIM', current_timestamp),
(55, 'THMSMC', 'Thames Magistrates', true, null, 'TIM', current_timestamp),
(56, 'WDGRCC', 'Wood Green Crown', true, null, 'TIM', current_timestamp),
(57, 'WOOLCC', 'Woolwich Crown', true, null, 'TIM', current_timestamp),
(58, 'LLDUMC', 'Llandudno Magistrates', true, null, 'TIM', current_timestamp),
(59, 'BRNSMC', 'Barnsley Magistrates', true, null, 'TIM', current_timestamp),
(60, 'BDLNMC', 'Bedlington Magistrates', true, null, 'TIM', current_timestamp),
(61, 'BEVRMC', 'Beverley Magistrates', true, null, 'TIM', current_timestamp),
(62, 'BRADCT', 'Bradford County', true, null, 'TIM', current_timestamp),
(63, 'BRADCC', 'Bradford Crown', true, null, 'TIM', current_timestamp),
(64, 'BRADMC', 'Bradford Magistrates', true, null, 'TIM', current_timestamp),
(65, 'PBORMC', 'Peterborough Magistrates', true, null, 'TIM', current_timestamp),
(66, 'NORWMC', 'Norwich Magistrates', true, null, 'TIM', current_timestamp),
(67, 'HERFCC', 'Hereford Crown', true, null, 'TIM', current_timestamp),
(68, 'IPSWCC', 'Ipswich Crown', true, null, 'TIM', current_timestamp),
(69, 'IPSWMC', 'Ipswich Magistrates', true, null, 'TIM', current_timestamp),
(70, 'NORWCC', 'Norwich Crown', true, null, 'TIM', current_timestamp),
(71, 'KNGSMC', 'Kings Lynn Magistrates', true, null, 'TIM', current_timestamp),
(72, 'GRTYMC', 'Great Yarmouth Magistrates', true, null, 'TIM', current_timestamp),
(73, 'NORWCT', 'Norwich County', true, null, 'TIM', current_timestamp),
(74, 'LEICMC', 'Leicester Magistrates', true, null, 'TIM', current_timestamp),
(75, 'LEICCC', 'Leicester Crown', true, null, 'TIM', current_timestamp),
(76, 'GLOCCC', 'Gloucester Crown', true, null, 'TIM', current_timestamp),
(77, 'CANNMC', 'Cannock Magistrates', true, null, 'TIM', current_timestamp),
(78, 'NWCLMC', 'North Staffs Justice Centre', true, null, 'TIM', current_timestamp),
(79, 'LLNWMC', 'Llandrindod Wells Magistrates', true, null, 'TIM', current_timestamp),
(80, 'LGHBMC', 'Loughborough Magistrates', true, null, 'TIM', current_timestamp),
(81, 'LGHBCC', 'Loughborough Crown', true, null, 'TIM', current_timestamp),
(82, 'CRYDCC', 'Croydon Crown', true, null, 'TIM', current_timestamp),
(83, 'STAFCC', 'Stafford Crown', true, null, 'TIM', current_timestamp),
(84, 'WLSSMC', 'Walsall Magistrates', true, null, 'TIM', current_timestamp),
(85, 'STOKCC', 'Stoke on Trent Crown', true, null, 'TIM', current_timestamp),
(86, 'GLAIAC', 'IAC Glasgow', true, null, 'TIM', current_timestamp),
(87, 'BRAIAC', 'IAC Bradford', true, null, 'TIM', current_timestamp),
(88, 'MNCIAC', 'IAC Manchester', true, null, 'TIM', current_timestamp),
(89, 'BDFIAC', 'IAC Yarls Wood', true, null, 'TIM', current_timestamp),
(90, 'TAYIAC', 'IAC Taylor House', true, null, 'TIM', current_timestamp),
(91, 'HATIAC', 'IAC Hatton Cross', true, null, 'TIM', current_timestamp),
(92, 'BIRAIT', 'IAC Birmingham', true, null, 'TIM', current_timestamp),
(93, 'CLRKCT', 'Clerkenwell and Shoreditch County', true, null, 'TIM', current_timestamp),
(94, 'HRRWCC', 'Harrow Crown', true, null, 'TIM', current_timestamp),
(95, 'HSTNMC', 'Hastings Magistrates', true, null, 'TIM', current_timestamp),
(96, 'HERTCT', 'Hertford County and Family Court', true, null, 'TIM', current_timestamp),
(97, 'HGHBMC', 'Highbury Corner Magistrates', true, null, 'TIM', current_timestamp),
(98, 'LEWSCT', 'Lewes Crown', true, null, 'TIM', current_timestamp),
(99, 'LUTNMC', 'Luton and South Bedfordshire Magistrates', true, null, 'TIM', current_timestamp),
(100, 'PBORCT', 'Peterborough County', true, null, 'TIM', current_timestamp),
(101, 'READCT', 'Reading County Court and Family Court', true, null, 'TIM', current_timestamp),
(102, 'STHSCC', 'Southend Crown', true, null, 'TIM', current_timestamp),
(103, 'STALMC', 'St Albans Magistrates', true, null, 'TIM', current_timestamp),
(104, 'STEVMC', 'Stevenage Magistrates', true, null, 'TIM', current_timestamp),
(105, 'STRAMC', 'Stratford Magistrates', true, null, 'TIM', current_timestamp),
(106, 'THANCT', 'Thanet County Court and Family Court', true, null, 'TIM', current_timestamp),
(107, 'UXBRMC', 'Uxbridge Magistrates', true, null, 'TIM', current_timestamp),
(108, 'WATFCT', 'Watford County and Family Court', true, null, 'TIM', current_timestamp),
(109, 'CRT026', 'Willesden Magistrates', true, null, 'TIM', current_timestamp),
(110, 'WORTCT', 'Worthing County', true, null, 'TIM', current_timestamp),
(111, 'WORTMC', 'Worthing Magistrates', true, null, 'TIM', current_timestamp),
(112, 'KNGSCC', 'Kings Lynn Crown', true, null, 'TIM', current_timestamp),
(113, 'MDSTCT', 'Maidstone County', true, null, 'TIM', current_timestamp),
(114, 'MDWYCT', 'Medway County', true, null, 'TIM', current_timestamp),
(115, 'CANTCT', 'Canterbury County', true, null, 'TIM', current_timestamp),
(116, 'BRIGFC', 'Brighton Family', true, null, 'TIM', current_timestamp),
(117, 'BROCFC', 'Bromley Civil and Family', true, null, 'TIM', current_timestamp),
(118, 'CHELJC', 'Chelmsford Justice Centre', true, null, 'TIM', current_timestamp),
(119, 'CRDCFC', 'Croydon Civil and Family', true, null, 'TIM', current_timestamp),
(120, 'ELONFC', 'East London Family Court', true, null, 'TIM', current_timestamp),
(121, 'ELTARB', 'East London Tribunals - Asylum Support', true, null, 'TIM', current_timestamp),
(122, 'EDMTFC', 'Edmonton Civil and Family', true, null, 'TIM', current_timestamp),
(123, 'GUCTFC', 'Guildford County Court and Family Court', true, null, 'TIM', current_timestamp),
(124, 'WNDCFC', 'Wandsworth Civil and Family', true, null, 'TIM', current_timestamp),
(125, 'HORSFC', 'Horsham Family', true, null, 'TIM', current_timestamp),
(126, 'IACHRM', 'IAC Harmondsworth', true, null, 'TIM', current_timestamp),
(127, 'KNGTCT', 'Kingston upon Thames County Court', true, null, 'TIM', current_timestamp),
(128, 'LTONJC', 'Luton Justice Centre', true, null, 'TIM', current_timestamp),
(129, 'RCJCNM', 'RCJ - Chancery Masters', true, null, 'TIM', current_timestamp),
(130, 'RCJLCT', 'RCJ - County Court at Central London', true, null, 'TIM', current_timestamp),
(131, 'RCJCAC', 'RCJ - Court of Appeal Civil', true, null, 'TIM', current_timestamp),
(132, 'RCJCCC', 'RCJ – Court of Appeal Criminal', true, null, 'TIM', current_timestamp),
(133, 'RCJHAC', 'RCJ - High Court Administrative Court', true, null, 'TIM', current_timestamp),
(134, 'RCJHFC', 'RCJ - High Court Family Division', true, null, 'TIM', current_timestamp),
(135, 'RCJKBJ', 'RCJ - High Court Kings Bench (Judges)', true, null, 'TIM', current_timestamp),
(136, 'RCJKBM', 'RCJ - High Court Kings Bench (Masters)', true, null, 'TIM', current_timestamp),
(137, 'RCJIAC', 'RCJ - Insolvency and Companies', true, null, 'TIM', current_timestamp),
(138, 'RCJMAC', 'RCJ - Mayors and City', true, null, 'TIM', current_timestamp),
(139, 'SSSCST', 'Sutton Social Security and Child Support Tribunal', true, null, 'TIM', current_timestamp),
(140, 'UTIACH', 'UTIAC Field House', true, null, 'TIM', current_timestamp),
(141, 'UXCAFC', 'Uxbridge Civil and Family Court', true, null, 'TIM', current_timestamp),
(142, 'WLSHCT', 'Welshpool County', true, null, 'TIM', current_timestamp),
(143, 'WLSHMC', 'Welshpool Magistrates', true, null, 'TIM', current_timestamp),
(144, 'WLVRCC', 'Wolverhampton Crown', true, null, 'TIM', current_timestamp),
(145, 'WLVRMC', 'Wolverhampton Magistrates', true, null, 'TIM', current_timestamp),
(146, 'WRCSCC', 'Worcester Crown', true, null, 'TIM', current_timestamp),
(147, 'WRCSMC', 'Worcester Magistrates', true, null, 'TIM', current_timestamp),
(148, 'WREXCT', 'Wrexham County', true, null, 'TIM', current_timestamp),
(149, 'WREXMC', 'Wrexham Magistrates', true, null, 'TIM', current_timestamp),
(150, 'CANTCC', 'Canterbury Crown', true, null, 'TIM', current_timestamp),
(151, 'CANTMC', 'Canterbury Magistrates', true, null, 'TIM', current_timestamp),
(152, 'FLKSMC', 'Folkestone Magistrates', true, null, 'TIM', current_timestamp),
(153, 'MDSTCC', 'Maidstone Crown', true, null, 'TIM', current_timestamp),
(154, 'WLONFC', 'West London Family Court', true, null, 'TIM', current_timestamp),
(155, 'MDSTMC', 'Maidstone Magistrates', true, null, 'TIM', current_timestamp),
(156, 'MRGTMC', 'Margate Magistrates', true, null, 'TIM', current_timestamp),
(157, 'CHTHMC', 'Medway Magistrates', true, null, 'TIM', current_timestamp),
(158, 'WDECFC', 'Willesden Civil and Family', true, null, 'TIM', current_timestamp),
(159, 'WORGFC', 'Worthing Family', true, null, 'TIM', current_timestamp),
(160, 'HASTFC', 'Hastings Family', true, null, 'TIM', current_timestamp),
(161, 'CBODMC', 'Bodmin Magistrates', true, null, 'TIM', current_timestamp),
(162, 'PLYMMC', 'Plymouth Magistrates', true, null, 'TIM', current_timestamp),
(163, 'CARLCT', 'Carlisle County', true, null, 'TIM', current_timestamp),
(164, 'CARLCC', 'Carlisle Crown', true, null, 'TIM', current_timestamp),
(165, 'CARLMC', 'Carlisle Magistrates', true, null, 'TIM', current_timestamp),
(166, 'DONCCT', 'Doncaster County', true, null, 'TIM', current_timestamp),
(167, 'DONCCC', 'Doncaster Crown', true, null, 'TIM', current_timestamp),
(168, 'DONCMC', 'Doncaster Magistrates', true, null, 'TIM', current_timestamp),
(169, 'DURHCT', 'Durham County', true, null, 'TIM', current_timestamp),
(170, 'DURHCC', 'Durham Crown', true, null, 'TIM', current_timestamp),
(171, 'GTSHMC', 'Gateshead Magistrates', true, null, 'TIM', current_timestamp),
(172, 'GRIMCT', 'Grimsby County', true, null, 'TIM', current_timestamp),
(173, 'GRIMCC', 'Grimsby Crown', true, null, 'TIM', current_timestamp),
(174, 'GRIMMC', 'Grimsby Magistrates', true, null, 'TIM', current_timestamp),
(175, 'HRRGMC', 'Harrogate Magistrates', true, null, 'TIM', current_timestamp),
(176, 'KNGHCT', 'Hull County', true, null, 'TIM', current_timestamp),
(177, 'KINGCC', 'Hull Crown', true, null, 'TIM', current_timestamp),
(178, 'KNGHMC', 'Hull Magistrates', true, null, 'TIM', current_timestamp),
(179, 'HUDRMC', 'Kirklees Magistrates', true, null, 'TIM', current_timestamp),
(180, 'LEEDCC', 'Leeds County', true, null, 'TIM', current_timestamp),
(181, 'LEEDCT', 'Leeds Crown', true, null, 'TIM', current_timestamp),
(182, 'LEEDMC', 'Leeds Magistrates', true, null, 'TIM', current_timestamp),
(183, 'NWCSCT', 'Newcastle-Upon-Tyne County', true, null, 'TIM', current_timestamp),
(184, 'NWCSCC', 'Newcastle-Upon-Tyne Crown', true, null, 'TIM', current_timestamp),
(185, 'NWCSMC', 'Newcastle-Upon-Tyne Magistrates', true, null, 'TIM', current_timestamp),
(186, 'NWAYMC', 'Newton Aycliffe Magistrates', true, null, 'TIM', current_timestamp),
(187, 'NRTSMC', 'North Tyneside Magistrates', true, null, 'TIM', current_timestamp),
(188, 'PTRLMC', 'Peterlee Magistrates', true, null, 'TIM', current_timestamp),
(189, 'SCBNMC', 'Scarborough Magistrates', true, null, 'TIM', current_timestamp),
(190, 'SHEFCT', 'Sheffield County', true, null, 'TIM', current_timestamp),
(191, 'SHEFCC', 'Sheffield Crown', true, null, 'TIM', current_timestamp),
(192, 'SHEFMC', 'Sheffield Magistrates', true, null, 'TIM', current_timestamp),
(193, 'STHMMC', 'South Tyneside Magistrates', true, null, 'TIM', current_timestamp),
(194, 'SUNDMC', 'Sunderland Magistrates', true, null, 'TIM', current_timestamp),
(195, 'TEESCT', 'Teesside County', true, null, 'TIM', current_timestamp),
(196, 'MDDLMC', 'Teesside Magistrates', true, null, 'TIM', current_timestamp),
(197, 'TEESCC', 'Teesside Crown', true, null, 'TIM', current_timestamp),
(198, 'WORNMC', 'Workington Magistrates', true, null, 'TIM', current_timestamp),
(199, 'YORKCT', 'York County', true, null, 'TIM', current_timestamp),
(200, 'YORKCC', 'York Crown', true, null, 'TIM', current_timestamp),
(201, 'YORKMC', 'York Magistrates', true, null, 'TIM', current_timestamp),
(202, 'GLDFCC', 'Guildford Crown', true, null, 'TIM', current_timestamp),
(203, 'GLDFMC', 'Guildford Magistrates', true, null, 'TIM', current_timestamp),
(204, 'STAIMC', 'Staines Magistrates', true, null, 'TIM', current_timestamp),
(205, 'ISLWCC', 'Isleworth Crown', true, null, 'TIM', current_timestamp),
(206, 'SNARCC', 'Snaresbrook Crown', true, null, 'TIM', current_timestamp),
(207, 'BRRWMC', 'Barrow Magistrates', true, null, 'TIM', current_timestamp),
(208, 'LANCMC', 'Lancaster Magistrates', true, null, 'TIM', current_timestamp),
(209, 'BURNMC', 'Burnley Magistrates', true, null, 'TIM', current_timestamp),
(210, 'BURNCC', 'Burnley Crown', true, null, 'TIM', current_timestamp),
(211, 'BLKBMC', 'Blackburn Magistrates', true, null, 'TIM', current_timestamp),
(212, 'PRESCC', 'Preston Crown Ringway', true, null, 'TIM', current_timestamp),
(213, 'PRESCT', 'Preston Crown Sessions House', true, null, 'TIM', current_timestamp),
(214, 'PRESMC', 'Preston Magistrates', true, null, 'TIM', current_timestamp),
(215, 'BLKPMC', 'Blackpool Magistrates', true, null, 'TIM', current_timestamp),
(216, 'CRT027', 'Barkingside Magistrates', true, null, 'TIM', current_timestamp),
(217, 'BRNTCT', 'Barnet Civil and Family Court', true, null, 'TIM', current_timestamp),
(218, 'BSLDCT', 'Basildon County', true, null, 'TIM', current_timestamp),
(219, 'BSLDCC', 'Basildon Crown', true, null, 'TIM', current_timestamp),
(220, 'BSLDMC', 'Basildon Magistrates', true, null, 'TIM', current_timestamp),
(221, 'BEXLMC', 'Bexley Magistrates', true, null, 'TIM', current_timestamp),
(222, 'BRTFCT', 'Brentford Civil and Family Court', true, null, 'TIM', current_timestamp),
(223, 'BRGHCT', 'Brighton County', true, null, 'TIM', current_timestamp),
(224, 'BRGEMC', 'Brighton Magistrates', true, null, 'TIM', current_timestamp),
(225, 'CNTRCC', 'Central Criminal Court', true, null, 'TIM', current_timestamp),
(226, 'CHLMCC', 'Chelmsford Crown', true, null, 'TIM', current_timestamp),
(227, 'CHLMMC', 'Chelmsford Magistrates', true, null, 'TIM', current_timestamp),
(228, 'COLTMC', 'Colchester Magistrates', true, null, 'TIM', current_timestamp),
(229, 'CRAWMC', 'Crawley Magistrates', true, null, 'TIM', current_timestamp),
(230, 'DRTFCT', 'Dartford County Court and Family Court', true, null, 'TIM', current_timestamp),
(231, 'EALNMC', 'Ealing Magistrates', true, null, 'TIM', current_timestamp),
(232, 'HATFMC', 'Hatfield Magistrates', true, null, 'TIM', current_timestamp),
(233, 'HNDNMC', 'Hendon Magistrates', true, null, 'TIM', current_timestamp),
(234, 'HWYCCT', 'High Wycombe County Court', true, null, 'TIM', current_timestamp),
(235, 'HRSHCT', 'Horsham County', true, null, 'TIM', current_timestamp),
(236, 'HRSHMC', 'Horsham Magistrates', true, null, 'TIM', current_timestamp),
(237, 'LUTNCC', 'Luton Crown', true, null, 'TIM', current_timestamp),
(238, 'MLTKCT', 'Milton Keynes County Court and Family Court', true, null, 'TIM', current_timestamp),
(239, 'OXFDCT', 'Oxford County', true, null, 'TIM', current_timestamp),
(240, 'RMFRCT', 'Romford County', true, null, 'TIM', current_timestamp),
(241, 'RMFRMC', 'Romford Magistrates', true, null, 'TIM', current_timestamp),
(242, 'SLOUCT', 'Slough County Court and Family Court', true, null, 'TIM', current_timestamp),
(243, 'STHSMC', 'Southend Magistrates', true, null, 'TIM', current_timestamp),
(244, 'STALCC', 'St Albans Crown', true, null, 'TIM', current_timestamp),
(245, 'HSTNCT', 'Hastings County', true, null, 'TIM', current_timestamp),
(246, 'TRURCC', 'Truro Crown', true, null, 'TIM', current_timestamp),
(247, 'TRURMC', 'Truro Magistrates', true, null, 'TIM', current_timestamp),
(248, 'PLYMCC', 'Plymouth Crown', true, null, 'TIM', current_timestamp),
(249, 'NWTAMC', 'Newton Abbot Magistrates', true, null, 'TIM', current_timestamp),
(250, 'EXETCC', 'Exeter Crown', true, null, 'TIM', current_timestamp),
(251, 'EXETMC', 'Exeter Magistrates', true, null, 'TIM', current_timestamp),
(252, 'BNSTMC', 'Barnstaple Magistrates', true, null, 'TIM', current_timestamp),
(253, 'WEYMMC', 'Weymouth Magistrates', true, null, 'TIM', current_timestamp),
(254, 'BRNMCC', 'Bournemouth Crown', true, null, 'TIM', current_timestamp),
(255, 'POOLMC', 'Poole Magistrates', true, null, 'TIM', current_timestamp),
(256, 'TAUNCC', 'Taunton Crown', true, null, 'TIM', current_timestamp),
(257, 'TAUNMC', 'Taunton Magistrates', true, null, 'TIM', current_timestamp),
(258, 'YEOVMC', 'Yeovil Magistrates', true, null, 'TIM', current_timestamp),
(259, 'BATHMC', 'Bath Magistrates', true, null, 'TIM', current_timestamp),
(260, 'WSPMMC', 'Weston-Super-Mare Magistrates', true, null, 'TIM', current_timestamp),
(261, 'BRSTCC', 'Bristol Crown', true, null, 'TIM', current_timestamp),
(262, 'BRSTMC', 'Bristol Magistrates', true, null, 'TIM', current_timestamp),
(263, 'SALSCC', 'Salisbury Crown', true, null, 'TIM', current_timestamp),
(264, 'SALSMC', 'Salisbury Magistrates', true, null, 'TIM', current_timestamp),
(265, 'SOUTCC', 'Southampton Crown', true, null, 'TIM', current_timestamp),
(266, 'SOUTMC', 'Southampton Magistrates', true, null, 'TIM', current_timestamp),
(267, 'WNCHCC', 'Winchester Crown', true, null, 'TIM', current_timestamp),
(268, 'BSNGMC', 'Basingstoke Magistrates', true, null, 'TIM', current_timestamp),
(269, 'ALDRMC', 'Aldershot Magistrates', true, null, 'TIM', current_timestamp),
(270, 'PRTSMC', 'Portsmouth Magistrates', true, null, 'TIM', current_timestamp),
(271, 'PRTSCC', 'Portsmouth Crown', true, null, 'TIM', current_timestamp),
(272, 'IOWICC', 'Isle of Wight Crown', true, null, 'TIM', current_timestamp),
(273, 'IOWIMC', 'Isle of Wight Magistrates', true, null, 'TIM', current_timestamp),
(274, 'LINCMC', 'Lincoln Magistrates', true, null, 'TIM', current_timestamp),
(275, 'BOSTMC', 'Boston Magistrates', true, null, 'TIM', current_timestamp),
(276, 'RCULON', 'RCU - London', true, null, 'TIM', current_timestamp),
(277, 'RCUMID', 'RCU - Midlands', true, null, 'TIM', current_timestamp),
(278, 'RCUNOR', 'RCU - North', true, null, 'TIM', current_timestamp),
(279, 'RCUSET', 'RCU - South East', true, null, 'TIM', current_timestamp),
(280, 'RCUWSW', 'RCU - Wales and South West', true, null, 'TIM', current_timestamp),
(281, 'LINCCC', 'Lincoln Crown', true, null, 'TIM', current_timestamp),
(282, 'CENTFC', 'Central Family Court', true, null, 'TIM', current_timestamp),
(283, 'CHESCC', 'Chester Crown', true, null, 'TIM', current_timestamp),
(284, 'CHESMC', 'Chester Magistrates', true, null, 'TIM', current_timestamp),
(285, 'CREWMC', 'Crewe Magistrates', true, null, 'TIM', current_timestamp),
(286, 'LPOLCC', 'Liverpool Crown', true, null, 'TIM', current_timestamp),
(287, 'LPOLMC', 'Liverpool Magistrates', true, null, 'TIM', current_timestamp),
(288, 'SEFTMC', 'Sefton Magistrates', true, null, 'TIM', current_timestamp),
(289, 'WRRNMC', 'Warrington Magistrates', true, null, 'TIM', current_timestamp),
(290, 'WIRLMC', 'Wirral Magistrates', true, null, 'TIM', current_timestamp),
(291, 'ENFLON', 'ENF - London', true, null, 'TIM', current_timestamp),
(292, 'CARDCC', 'Cardiff Crown', true, null, 'TIM', current_timestamp),
(293, 'CARDMC', 'Cardiff Magistrates', true, null, 'TIM', current_timestamp),
(294, 'CWMBMC', 'Cwmbran Magistrates', true, null, 'TIM', current_timestamp),
(295, 'HAVEMC', 'Haverfordwest Magistrates', true, null, 'TIM', current_timestamp),
(296, 'HAVECC', 'Haverfordwest Crown', true, null, 'TIM', current_timestamp),
(297, 'LLANMC', 'Llanelli Magistrates', true, null, 'TIM', current_timestamp),
(298, 'MERTCC', 'Merthyr Tydfil Crown', true, null, 'TIM', current_timestamp),
(299, 'MERTMC', 'Merthyr Tydfil Magistrates', true, null, 'TIM', current_timestamp),
(300, 'NEWPCC', 'Newport Crown', true, null, 'TIM', current_timestamp),
(301, 'NEWPMC', 'Newport Magistrates', true, null, 'TIM', current_timestamp),
(302, 'SWANCC', 'Swansea Crown', true, null, 'TIM', current_timestamp),
(303, 'SWANMC', 'Swansea Magistrates', true, null, 'TIM', current_timestamp),
(304, 'ABERCV', 'Aberystwyth Civil', true, null, 'TIM', current_timestamp),
(305, 'ABERFC', 'Aberystwyth Family', true, null, 'TIM', current_timestamp),
(306, 'BLACCV', 'Blackwood Civil', true, null, 'TIM', current_timestamp),
(307, 'BLACFC', 'Blackwood Family', true, null, 'TIM', current_timestamp),
(308, 'CARDCV', 'Cardiff Civil', true, null, 'TIM', current_timestamp),
(309, 'CARDFC', 'Cardiff Family', true, null, 'TIM', current_timestamp),
(310, 'CARMCV', 'Carmarthen Civil', true, null, 'TIM', current_timestamp),
(311, 'CARMFC', 'Carmarthen Family', true, null, 'TIM', current_timestamp),
(312, 'HAVECV', 'Haverfordwest Civil', true, null, 'TIM', current_timestamp),
(313, 'HAVEFC', 'Haverfordwest Family', true, null, 'TIM', current_timestamp),
(314, 'LLANCV', 'Llanelli Civil', true, null, 'TIM', current_timestamp),
(315, 'LLANFC', 'Llanelli Family', true, null, 'TIM', current_timestamp),
(316, 'MERTCV', 'Merthyr Tydfil Civil', true, null, 'TIM', current_timestamp),
(317, 'MERTFC', 'Merthyr Tydfil Family', true, null, 'TIM', current_timestamp),
(318, 'NEWPCV', 'Newport Civil', true, null, 'TIM', current_timestamp),
(319, 'NEWPFC', 'Newport Family', true, null, 'TIM', current_timestamp),
(320, 'PONTCV', 'Pontypridd Civil', true, null, 'TIM', current_timestamp),
(321, 'PONTFC', 'Pontypridd Family', true, null, 'TIM', current_timestamp),
(322, 'PORTCV', 'Port Talbot Civil', true, null, 'TIM', current_timestamp),
(323, 'PORTFC', 'Port Talbot Family', true, null, 'TIM', current_timestamp),
(324, 'SWANCV', 'Swansea Civil', true, null, 'TIM', current_timestamp),
(325, 'SWANFC', 'Swansea Family', true, null, 'TIM', current_timestamp),
(326, 'ABERMC', 'Aberystwyth Magistrates', true, null, 'TIM', current_timestamp);

alter sequence if exists court_court_id_seq restart with 327;

---

insert into court_contact (court_contact_id, court_id, name, email, telephone, position, enabled, notes, primary_contact, created_by, created_time)
values (1, 1, 'John Hipkins', 'j@j.com', '0117 282442', 'Court Clerk', true, '', true, 'TIM', current_timestamp),
       (2, 1, 'Matt Hipkins', 'm@m.com', '0117 282443', 'Court Clerk', true, '', false, 'TIM', current_timestamp),
       (3, 1, 'Steve Hipkins', 's@s.com', '0117 282444', 'Court Clerk', true, '', false, 'TIM', current_timestamp);

alter sequence if exists court_contact_court_contact_id_seq restart with 4;

---

insert into probation_team (probation_team_id, code, description, enabled, notes, created_by, created_time)
values (1, 'BLKPPP', 'Blackpool MC (PPOC)', true, null, 'TIM', current_timestamp),
       (2, 'BARSPP', 'RWF - Barkingside MC (PPOC)', true, null, 'TIM', current_timestamp),
       (3, 'PPOCFD', 'RWF - Redbridge (PPOC)', true, null, 'TIM', current_timestamp),
       (4, 'HGHBPP', 'CAI - Highbury Corner MC (PPOC)', true, null, 'TIM', current_timestamp),
       (5, 'PRESPC', 'Preston CC (PPOC)', true, null, 'TIM', current_timestamp),
       (6, 'PRESPM', 'Preston MC (PPOC)', true, null, 'TIM', current_timestamp),
       (7, 'BURNPC', 'Burnley CC (PPOC)', true, null, 'TIM', current_timestamp),
       (8, 'BURNPM', 'Burnley MC (PPOC)', true, null, 'TIM', current_timestamp),
       (9, 'BLKBPP', 'Blackburn MC (PPOC)', true, null, 'TIM', current_timestamp),
       (10, 'REMPSR', 'Remote PSR Team (PPOC)', true, null, 'TIM', current_timestamp),
       (11, 'CROYCC', 'CRO - Croydon CC (PPOC)', true, null, 'TIM', current_timestamp),
       (12, 'CROYMC', 'CRO - Croydon MC (PPOC)', true, null, 'TIM', current_timestamp),
       (13, 'ILONCC', 'SOU - Inner London CC (PPOC)', true, null, 'TIM', current_timestamp),
       (14, 'SWRKCC', 'SOU - Southwark CC (PPOC)', true, null, 'TIM', current_timestamp),
       (15, 'PPOCCT', 'RWF - Snaresbrook CC (PPOC)', true, null, 'TIM', current_timestamp),
       (16, 'WESTMC', 'HFKCW - Westminster MC (PPOC)', true, null, 'TIM', current_timestamp),
       (17, 'WIMBMC', 'WAN - Wimbledon MC (PPOC)', true, null, 'TIM', current_timestamp),
       (18, 'HARNGY', 'EAH - Haringey (PPOC)', true, null, 'TIM', current_timestamp),
       (19, 'BARNET', 'BAR - Barnet (PPOC)', true, null, 'TIM', current_timestamp),
       (20, 'HARROW', 'HRW - Harrow (PPOC)', true, null, 'TIM', current_timestamp),
       (21, 'WALFOR', 'RWF - Waltham Forest (PPOC)', true, null, 'TIM', current_timestamp),
       (22, 'THMSPP', 'TWR - Thames&Stratford MC (PPOC)', true, null, 'TIM', current_timestamp),
       (23, 'WDGNPP', 'HAR - Wood Green CC (PPOC)', true, null, 'TIM', current_timestamp),
       (24, 'KENSCC', 'KAR - Kingston CC (PPOC)', true, null, 'TIM', current_timestamp),
       (25, 'LANCPM', 'Lancaster MC (PPOC)', true, null, 'TIM', current_timestamp),
       (26, 'LANCNW', 'NW Lancashire (PPOC)', true, null, 'TIM', current_timestamp),
       (27, 'LANCEA', 'East Lancashire (PPOC)', true, null, 'TIM', current_timestamp),
       (28, 'LANCCE', 'Central Lancashire (PPOC)', true, null, 'TIM', current_timestamp);

alter sequence if exists probation_team_probation_team_id_seq restart with 29;

---

insert into probation_team_contact (probation_team_contact_id, probation_team_id, name, email, telephone, position, enabled, notes, primary_contact, created_by, created_time)
values (1, 1, 'Tim Hipkins', 't@t.com', '0117 282442', 'Court Clerk', true, '', true, 'TIM', current_timestamp),
       (2, 1, 'Matt Hipkins', 'm@m.com', '0117 282443', 'Court Clerk', true, '', false, 'TIM', current_timestamp),
       (3, 1, 'Steve Hipkins', 's@s.com', '0117 282444', 'Court Clerk', true, '', false, 'TIM', current_timestamp);

alter sequence if exists probation_team_contact_probation_team_contact_id_seq restart with 4;

---
-- Enabled here means enabled for self-service bookings by the courts / probation
-- Enabled = false means that the bookings can still be made by the prison, and exist in the DB, but cannot be created/edited by courts or probation.

insert into prison (prison_id, code, name, enabled, notes, created_by, created_time)
values (1,'WNI', 'Werrington (HMYOI)', false, null, 'TIM', current_timestamp),
       (2,'WYI', 'Wetherby (HM YOI)', false, null, 'TIM', current_timestamp),
       (3,'AA1', 'AA3 Prison for test', false, null, 'TIM', current_timestamp),
       (4,'FHI', 'Foston Hall (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (5,'HDI', 'Hatfield (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (6,'HOI', 'High Down (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (7,'HII', 'Hindley (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (8,'HBI', 'Hollesley Bay (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (9,'HLI', 'Hull (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (10,'LWI', 'Lewes (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (11,'LII', 'Lincoln (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (12,'LNI', 'Low Newton (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (13,'MDI', 'Moorland (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (14,'MHI', 'Morton Hall (HMP)', false, null, 'TIM', current_timestamp),
       (15,'NHI', 'New Hall (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (16,'NWI', 'Norwich (HMP & YOI)', true, null, 'TIM', current_timestamp),
       (17,'PVI', 'Pentonville (HMP & YOI)', true, null, 'TIM', current_timestamp),
       (18,'PDI', 'Portland (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (19,'RCI', 'Rochester (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (20,'SHI', 'Stoke Heath (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (21,'STI', 'Styal (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (22,'SUI', 'Sudbury (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (23,'SNI', 'Swinfen Hall (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (24,'TCI', 'Thorn Cross (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (25,'UKI', 'Usk (HMP)', false, null, 'TIM', current_timestamp),
       (26,'UPI', 'Prescoed (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (27,'WWI', 'Wandsworth (HMP & YOI)', true, null, 'TIM', current_timestamp),
       (28,'WII', 'Warren Hill (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (29,'WCI', 'Winchester (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (30,'WHI', 'Woodhill (HMP)', false, null, 'TIM', current_timestamp),
       (31,'WSI', 'Wormwood Scrubs (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (32,'WMI', 'Wymott (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (33,'BMI', 'Birmingham (HMP)', true, null, 'TIM', current_timestamp),
       (34,'BXI', 'Brixton (HMP)', false, null, 'TIM', current_timestamp),
       (35,'BCI', 'Buckley Hall (HMP)', false, null, 'TIM', current_timestamp),
       (36,'BRI', 'Bure (HMP)', false, null, 'TIM', current_timestamp),
       (37,'CWI', 'Channings Wood (HMP)', false, null, 'TIM', current_timestamp),
       (38,'CLI', 'Coldingley (HMP)', false, null, 'TIM', current_timestamp),
       (39,'DAI', 'Dartmoor (HMP)', false, null, 'TIM', current_timestamp),
       (40,'FSI', 'Featherstone (HMP)', false, null, 'TIM', current_timestamp),
       (41,'FDI', 'Ford (HMP)', false, null, 'TIM', current_timestamp),
       (42,'ABC', 'HMP New Prison2', false, null, 'TIM', current_timestamp),
       (43,'FKI', 'Frankland (HMP)', false, null, 'TIM', current_timestamp),
       (44,'FNI', 'Full Sutton (HMP)', false, null, 'TIM', current_timestamp),
       (45,'GHI', 'Garth (HMP)', false, null, 'TIM', current_timestamp),
       (46,'GTI', 'Gartree (HMP)', false, null, 'TIM', current_timestamp),
       (47,'GNI', 'Grendon (HMP)', false, null, 'TIM', current_timestamp),
       (48,'GMI', 'Guys Marsh (HMP)', false, null, 'TIM', current_timestamp),
       (49,'HVI', 'Haverigg (HMP)', false, null, 'TIM', current_timestamp),
       (50,'HEI', 'Hewell (HMP)', true, null, 'TIM', current_timestamp),
       (51,'HPI', 'Highpoint (HMP)', false, null, 'TIM', current_timestamp),
       (52,'HMI', 'Humber (HMP)', false, null, 'TIM', current_timestamp),
       (53,'HCI', 'Huntercombe (HMP)', false, null, 'TIM', current_timestamp),
       (54,'KMI', 'Kirkham (HMP)', false, null, 'TIM', current_timestamp),
       (55,'LFI', 'Lancaster Farms (HMP)', false, null, 'TIM', current_timestamp),
       (56,'LEI', 'Leeds (HMP)', false, null, 'TIM', current_timestamp),
       (57,'LCI', 'Leicester (HMP)', false, null, 'TIM', current_timestamp),
       (58,'LYI', 'Leyhill (HMP)', false, null, 'TIM', current_timestamp),
       (59,'LHI', 'Lindholme (HMP)', false, null, 'TIM', current_timestamp),
       (60,'LTI', 'Littlehey (HMP)', false, null, 'TIM', current_timestamp),
       (61,'LPI', 'Liverpool (HMP)', false, null, 'TIM', current_timestamp),
       (62,'LLI', 'Long Lartin (HMP)', false, null, 'TIM', current_timestamp),
       (63,'MSI', 'Maidstone (HMP)', false, null, 'TIM', current_timestamp),
       (64,'NSI', 'North Sea Camp (HMP)', false, null, 'TIM', current_timestamp),
       (65,'ONI', 'Onley (HMP)', false, null, 'TIM', current_timestamp),
       (66,'RNI', 'Ranby (HMP)', false, null, 'TIM', current_timestamp),
       (67,'RSI', 'Risley (HMP)', false, null, 'TIM', current_timestamp),
       (68,'SDI', 'Send (HMP)', false, null, 'TIM', current_timestamp),
       (69,'SPI', 'Spring Hill (HMP)', false, null, 'TIM', current_timestamp),
       (70,'SFI', 'Stafford (HMP)', false, null, 'TIM', current_timestamp),
       (71,'SKI', 'Stocken (HMP)', false, null, 'TIM', current_timestamp),
       (72,'SLI', 'Swaleside (HMP)', false, null, 'TIM', current_timestamp),
       (73,'MTI', 'The Mount (HMP)', false, null, 'TIM', current_timestamp),
       (74,'VEI', 'The Verne (HMP)', false, null, 'TIM', current_timestamp),
       (75,'WDI', 'Wakefield (HMP)', false, null, 'TIM', current_timestamp),
       (76,'WLI', 'Wayland (HMP)', false, null, 'TIM', current_timestamp),
       (77,'WEI', 'Wealstun (HMP)', false, null, 'TIM', current_timestamp),
       (78,'WTI', 'Whatton (HMP)', false, null, 'TIM', current_timestamp),
       (79,'WRI', 'Whitemoor (HMP)', false, null, 'TIM', current_timestamp),
       (80,'AYI', 'Aylesbury (HMYOI)', false, null, 'TIM', current_timestamp),
       (81,'BFI', 'Bedford (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (82,'BAI', 'Belmarsh (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (83,'BWI', 'Berwyn (HMP & YOI)', true, null, 'TIM', current_timestamp),
       (84,'BSI', 'Brinsford (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (85,'BLI', 'Bristol (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (86,'BNI', 'Bullingdon (HMP & YOI)', true, null, 'TIM', current_timestamp),
       (87,'CFI', 'Cardiff (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (88,'CDI', 'Chelmsford (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (89,'CKI', 'Cookham Wood (HMYOI)', false, null, 'TIM', current_timestamp),
       (90,'DTI', 'Deerbolt (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (91,'DWI', 'Downview (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (92,'DHI', 'Drake Hall (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (93,'FMI', 'Feltham (HMP)', false, null, 'TIM', current_timestamp),
       (94,'FYI', 'Feltham (HMYOI)', false, null, 'TIM', current_timestamp),
       (95,'DMI', 'Durham (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (96,'ESI', 'East Sutton Park (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (97,'EWI', 'Eastwood Park (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (98,'EYI', 'Elmley (HMP & YOI)', true, null, 'TIM', current_timestamp),
       (99,'EEI', 'Erlestoke (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (100,'EXI', 'Exeter (HMP & YOI)', true, null, 'TIM', current_timestamp),
       (101,'HHI', 'Holme House (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (102,'ISI', 'Isis (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (103,'IWI', 'Isle Of Wight (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (104,'KVI', 'Kirklevington Grange (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (105,'MRI', 'Manchester (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (106,'NMI', 'Nottingham (HMP & YOI)', true, null, 'TIM', current_timestamp),
       (107,'PNI', 'Preston (HMP & YOI)', true, null, 'TIM', current_timestamp),
       (108,'EHI', 'Standford Hill (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (109,'SWI', 'Swansea (HMP & YOI)', false, null, 'TIM', current_timestamp),
       (110,'TSI', 'Thameside (HMP)', true, null, 'TIM', current_timestamp),
       (111,'PBI', 'Peterborough (HMP)', true, null, 'TIM', current_timestamp),
       (112,'BZI', 'Bronzefield (HMP)', true, null, 'TIM', current_timestamp);

alter sequence if exists prison_prison_id_seq restart with 113;

---

insert into prison_contact (prison_contact_id, prison_id, name, email, telephone, position, enabled, notes, primary_contact, created_by, created_time)
values (1, 1, 'Tim Hopkins', 't@t.com', '0117 282442', 'Video Admin', true, '', true, 'TIM', current_timestamp),
       (2, 1, 'Matt Hopkins', 'm@m.com', '0117 282443', 'Video Admin', true, '', false, 'TIM', current_timestamp),
       (3, 1, 'Steve Hopkins', 's@s.com', '0117 282444', 'Video Admin', true, '', false, 'TIM', current_timestamp),
       (4, 33, 'Jane Hopkins', 'j@j.com', '0117 282445', 'Video Admin', true, '', true, 'TIM', current_timestamp),
       (5, 16, 'Robbie Hopkins', 'r@r.com', '0117 282446', 'Video Admin', true, '', true, 'TIM', current_timestamp);

alter sequence if exists prison_contact_prison_contact_id_seq restart with 6;
