-- New probation teams
insert into probation_team (code, description, enabled, read_only, notes, created_by, created_time)
values
    ( 'BARNMG', 'Barnsley Magistrates - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'BEVEMG', 'Beverley Magistrates - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'BRFDCC', 'Bradford Crown - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'BRFDMG', 'Bradford Magistrates - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'DONCCC', 'Doncaster Crown - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'DONCMG', 'Doncaster Magistrates - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'GRIMCC', 'Grimsby Crown - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'GRIMMG', 'Grimsby Magistrates - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'HARRMG', 'Harrogate Magistrates - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'HUHSMG', 'Hull and Holderness Magistrates - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'HULLCC', 'Hull Crown - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'KIRKMG', 'Kirkless Magistrates - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'LEEDMG', 'Leeds Magistrates - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'LEEDCC', 'Leeds Crown - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'SCARMG', 'Scarborough Magistrates - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'SHEFCC', 'Sheffield Crown - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'SHEFMG', 'Sheffield Magistrates - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'SKIPMG', 'Skipton Magistrates - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'YORKCC', 'York Crown - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'YORKMG', 'York Magistrates - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'ABERMG', 'Aberystwyth Magistrates - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'CAERCC', 'Caernarfon Crown - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'CAERMG', 'Caernarfon Magistrates - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'LLANMG', 'Llandrindod Magistrates - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'LLNDMG', 'Llandudno Magistrates - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'MOLDCC', 'Mold Crown - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'MOLDMG', 'Mold Magistrates - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'WLSHMG', 'Welshpool Magistrates - Probation', true, false, null, 'TIM', current_timestamp),
    ( 'WREXMG', 'Wrexham Magistrates - Probation', true, false, null, 'TIM', current_timestamp);
