generic-service:
  nameOverride: hmpps-book-a-video-link-api
  productId: "DPS093" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-book-a-video-link-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-book-a-video-link-api-cert
    path: /
    annotations:
      # Secure the endpoints related to k8s jobs from outside the Kubernetes ingress
      nginx.ingress.kubernetes.io/server-snippet: |
        server_tokens off;
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }

  # Used to access resources like SQS queues and SNS topics
  serviceAccountName: hmpps-book-a-video-link

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    DB_SSL_MODE: "verify-full"
    FEATURE_EVENTS_SNS_ENABLED: false
    HMPPS_SQS_USE_WEB_TOKEN: true

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-book-a-video-link-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
    rds-postgresql-instance-output:
      DB_SERVER: "rds_instance_address"
      DB_NAME: "database_name"
      DB_USER: "database_username"
      DB_PASS: "database_password"
    gov-notify:
      NOTIFY_API_KEY: "notify_api_key"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ARN: "topic_arn"
    sqs-domain-event-secret:
      HMPPS_SQS_QUEUES_BVLS_QUEUE_NAME: "sqs_queue_name"
    sqs-domain-event-dlq-secret:
      HMPPS_SQS_QUEUES_BVLS_DLQ_NAME: "sqs_queue_name"

  allowlist:
    groups:
      - internal
      - prisons

generic-prometheus-alerts:
  targetApplication: hmpps-book-a-video-link-api
  sqsAlertsTotalMessagesThreshold: "0"
