spring:
  flyway:
    locations: classpath:/migrations/common,classpath:/migrations/dev

notify:
  templates:
    probation:
      new-booking:
        user: "31d92a30-e67b-4bd8-856c-415b57ba0f7b"
        prison-probation-email: "1d1e4265-7c58-4597-a0eb-1d77ec26ac5f"
        prison-no-probation-email: "a39260ea-6cdc-42e1-8c9d-4018f50b2cc5"
      amended-booking:
        user: "cd864c20-249a-4301-a5f7-21821a215895"
        probation: "c4d66183-1a81-46d0-9248-da7d0e6d4c9b"
        prison-probation-email: "26ef42c1-e09c-44b2-a5cf-eb4a8c2589e2"
        prison-no-probation-email: "8e4b04a5-7811-4498-9689-1d914b095b33"
