spring:
  flyway:
    locations: classpath:/migrations/common,classpath:/migrations/dev

notify:
  templates:
    probation:
      cancelled-booking:
        user: "c0f0834d-7343-4af4-8df2-bfd3c970e836"
        probation: "df97c314-cb5d-48ce-9241-7d94ea98e323"
        prison-probation-email: "8bdf8c4e-c15c-4621-9469-035fa14c9daa"
        prison-no-probation-email: "b090bedf-58da-495a-8d94-76e4f64aedf8"
  