#
# The "-local" profile is for running the API service locally against pre-existing
# docker containers that are listening on a known port numbers for a postgres database (5432).
#

# Most values are inherited from - application.yml - except the following:
spring:
  jpa:
    show-sql: true

  flyway:
    locations: classpath:/migrations/common,classpath:/migrations/dev

system:
  client:
    id: ${SYSTEM_CLIENT_ID}
    secret: ${SYSTEM_CLIENT_SECRET}

# External dependent service DEV URLs
api:
  base:
    url:
      activities-appointments: https://activities-api-dev.prison.service.justice.gov.uk
      hmpps-auth: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
      locations-inside-prison: https://locations-inside-prison-api-dev.hmpps.service.justice.gov.uk
      manage-users: https://manage-users-api-dev.hmpps.service.justice.gov.uk
      prison-api: https://prison-api-dev.prison.service.justice.gov.uk
      prisoner-search: https://prisoner-search-dev.prison.service.justice.gov.uk
      nomis-mapping: https://nomis-sync-prisoner-mapping-dev.hmpps.service.justice.gov.uk
bvls:
  frontend:
    url: http://localhost:3000

hmpps.sqs:
  provider: localstack
  queues:
    bvls:
      queueName: bvls-queue
      subscribeFilter: '{"eventType":[ "book-a-video-link.video-booking.created", "book-a-video-link.video-booking.amended", "book-a-video-link.video-booking.cancelled", "book-a-video-link.appointment.created", "prisoner-offender-search.prisoner.released", "prison-offender-events.prisoner.merged", "prison-offender-events.prisoner.video-appointment.cancelled"]}'
      dlqName: bvls-dead-letter-queue
      subscribeTopicId: domainevents
      dlqMaxReceiveCount: 1
      visibilityTimeout: 1
    domaineventsqueue:
      queueName: domainevents-queue
      subscribeTopicId: domainevents
    outboundtestqueue:
      dlqName: ${random.uuid}
      queueName: ${random.uuid}
      subscribeTopicId: outboundtopic
      subscribeFilter: '{"eventType":[ "test.type"] }'
    audit:
      queueName: ${random.uuid}
  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:domainevents-topic
    outboundtopic:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}
