info.app:
  name: Hmpps Book A Video Link Api
  version: 1.0

spring:
  application:
    name: hmpps-book-a-video-link-api
  codec:
    max-in-memory-size: 10MB

  datasource:
    url: 'jdbc:postgresql://${DB_SERVER}/${DB_NAME}?sslmode=${DB_SSL_MODE}'
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    open-in-view: false
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

  flyway:
    locations: classpath:/migrations/common

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-leniency: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${api.base.url.hmpps-auth}/.well-known/jwks.json
      client:
        registration:
          activities-appointments:
            provider: hmpps-auth
            client-id: ${system.client.id}
            client-secret: ${system.client.secret}
            authorization-grant-type: client_credentials
            scope: read,write
          locations-inside-prison:
            provider: hmpps-auth
            client-id: ${system.client.id}
            client-secret: ${system.client.secret}
            authorization-grant-type: client_credentials
            scope: read
          manage-users:
            provider: hmpps-auth
            client-id: ${system.client.id}
            client-secret: ${system.client.secret}
            authorization-grant-type: client_credentials
            scope: read
          prisoner-api:
            provider: hmpps-auth
            client-id: ${system.client.id}
            client-secret: ${system.client.secret}
            authorization-grant-type: client_credentials
            scope: read,write
          prisoner-search:
            provider: hmpps-auth
            client-id: ${system.client.id}
            client-secret: ${system.client.secret}
            authorization-grant-type: client_credentials
            scope: read
          whereabouts-api:
            provider: hmpps-auth
            client-id: ${system.client.id}
            client-secret: ${system.client.secret}
            authorization-grant-type: client_credentials
            scope: read
          nomis-mapping-api:
            provider: hmpps-auth
            client-id: ${system.client.id}
            client-secret: ${system.client.secret}
            authorization-grant-type: client_credentials
            scope: read
        provider:
          hmpps-auth:
            token-uri: ${api.base.url.hmpps-auth}/oauth/token
  task:
    execution:
      thread-name-prefix: async-thread-
      pool:
        core-size: 2
        max-size: 4
        queue-capacity: 50

  mvc:
    async:
      request-timeout: 60000 # one minute request timeout

server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
      internal-proxies: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}|0:0:0:0:0:0:0:1|::1|100\.6[4-9]\.\d{1,3}\.\d{1,3}|100\.[7-9][0-9]{1}\.\d{1,3}\.\d{1,3}|100\.1[0-1][0-9]{1}\.\d{1,3}\.\d{1,3}|100\.12[0-7]\.\d{1,3}\.\d{1,3}
  shutdown: graceful
  error:
    include-message: always

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
      probes:
        enabled: true
    info:
      cache:
        time-to-live: 2000ms

notify:
  templates:
    court:
      new-booking:
        user: "b1a3c944-d0d3-4846-94ca-ca03373b7d40"
        court: "c6a1abba-125e-4936-bd20-7a5e14ee2ffe"
        prison-court-email: "9e4d64e1-5b81-4f06-a43e-63eacc46f865"
        prison-no-court-email: "ae433efa-a2a6-47c6-8165-54ed8a8f9dc1"
      amended-booking:
        user: "fb5c7f72-2f20-4009-adef-0defe304f486"
        court: "16c1e0cb-41bf-484e-aa0f-80161a0715ed"
        prison-court-email: "2d08400e-012d-44a0-a110-3904f54bc006"
        prison-no-court-email: "35a771f3-14f7-44be-ac73-fec8f0ee056e"
      cancelled-booking:
        user: "946a129a-ed09-40ca-b0ac-a39ec6c1bc2b"
        court: "cfac8ef0-dc03-403b-bf8b-bea6356561ff"
        prison-court-email: "9c80bb57-abed-4316-8404-cbdcd48b8f25"
        prison-no-court-email: "602981eb-cc7f-4a85-aba3-577167f1ee83"
      booking-request:
        user: "fcc3f591-81c2-4b8d-9b3c-a4051cd19e9d"
        prison-court-email: "d6c04a5e-3866-4b7e-b892-f41add21f47a"
        prison-no-court-email: "7a1fe877-321c-4a3d-8c5a-af15e7432ba9"
      transfer-booking:
        court: "3fe1e9d5-3319-496c-90df-0115087cd31b"
        prison-court-email: "6fdf202b-01f9-48e7-b216-35c695f84df3"
        prison-no-court-email: "0498e8d9-a2ea-4e00-9e5c-96d1d3cd6cb9"
      release-booking:
        court: "55817f53-211c-442d-ac6f-f3fda3adee84"
        prison-court-email: "e5bbd8a8-f59c-4670-9ba3-fd4cda922a21"
        prison-no-court-email: "da59e795-aef6-4cb9-be68-54435df8c8b1"
      hearing-link-reminder:
        court: "2a067470-bc6b-4169-8c94-4733ed28a203"
    probation:
      booking-request:
        user: "d401c074-6914-4910-b29c-92b328951925"
        prison-probation-team-email: "a8f74eda-c327-4dde-88db-354843292c6c"
        prison-no-probation-team-email: "2326fa9d-1627-4c04-8c8d-a6e1ae19a6cb"
      new-booking:
        user: "20fddb45-3907-4e10-a570-86377bbe9dd1"
        prison-probation-email: "73a0e2b3-6b49-4a31-8960-973e3e833e81"
        prison-no-probation-email: "9701dd1e-ba93-49e9-94f4-2b335459d420"
      amended-booking:
        user: "a3c1c0f9-d86f-43bc-904c-c666d309111c"
        probation: "21ae0c83-69d2-4dc3-b19a-22c56500f67f"
        prison-probation-email: "1ccb289c-bd49-4421-8c1c-e56e99db9886"
        prison-no-probation-email: "d00804ff-25f8-45f8-b5a5-164c14e0d66f"
      cancelled-booking:
        user: "bf05f505-c60e-4b67-bac0-1a0660a03f94"
        probation: "09685f07-20e0-4fd9-9245-e726e500552e"
        prison-probation-email: "b5fdd441-ca5c-43e0-9e66-e3be27d7605d"
        prison-no-probation-email: "8c186bb6-92ba-4619-8633-630a214bcbea"
      release-booking:
        probation: "099cab2b-331e-46b3-a2eb-dd46e0979afd"
        prison-probation-email: "b2b36311-a787-408e-885c-df17b10e936b"
        prison-no-probation-email: "fb70890b-1c03-4122-8a5f-7c1a8a928e6c"
      transfer-booking:
        probation: "33cad270-00ae-4490-aecb-49d9607e74e4"
        prison-probation-email: "094b0fcb-e34b-4fc8-b06a-a5b80ca49c55"
        prison-no-probation-email: "333b332c-1b45-406a-8f58-6ae61b96d027"


springdoc:
  swagger-ui:
    tags-sorter: alpha

# Options to configure suggested alternative booking times
video-link-booking:
  options:
    day-start: "10:00"
    day-end: "17:00"
    step: "PT15M"
    max-alternatives: 3

hmpps:
  sqs:
    queueAdminRole: BOOK_A_VIDEO_LINK_ADMIN
