apiVersion: batch/v1
kind: CronJob
metadata:
  name: administration-new-video-room
spec:
  schedule:  "{{ .Values.cron.administrationNewVideoRoomJob }}"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 43200
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600 # 4 days
      template:
        spec:
          containers:
            - name: administration-new-video-room-job
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --fail --retry 2 -XPOST http://hmpps-book-a-video-link-api/job-admin/run/NEW_VIDEO_ROOM
          restartPolicy: Never
