#!/bin/bash

ENV=$1

BVLS_NAMESPACE="hmpps-book-a-video-link-$ENV"
FEATURE_MASTER_PUBLIC_PRIVATE_NOTES=$(kubectl -n "$BVLS_NAMESPACE" get secret feature-toggles -o jsonpath='{.data.FEATURE_MASTER_PUBLIC_PRIVATE_NOTES}' | base64 -d)
FEATURE_GREY_RELEASE_PRISONS=$(kubectl -n "$BVLS_NAMESPACE" get secret feature-toggles -o jsonpath='{.data.FEATURE_GREY_RELEASE_PRISONS}' | base64 -d)

ACTIVITIES_NAMESPACE="hmpps-activities-management-$ENV"
AA_BVLS_FEATURE_MASTER_PUBLIC_PRIVATE_NOTES=$(kubectl -n "$ACTIVITIES_NAMESPACE" get secret feature-toggles -o jsonpath='{.data.BVLS_FEATURE_MASTER_PUBLIC_PRIVATE_NOTES}' | base64 -d)

DIGITAL_PRISON_SERVICES="digital-prison-services-$ENV"
DPS_BVLS_PUBLIC_PRIVATE_NOTES_FEATURE_TOGGLE_ENABLED=$(kubectl -n "$DIGITAL_PRISON_SERVICES" get secret feature-toggles -o jsonpath='{.data.BVLS_PUBLIC_PRIVATE_NOTES_FEATURE_TOGGLE_ENABLED}' | base64 -d)

echo ENVIRONMENT="$ENV"
echo BVLS - PUBLIC_PRIVATE_NOTES="$FEATURE_MASTER_PUBLIC_PRIVATE_NOTES"
echo BVLS - GREY_RELEASE_PRISONS="$FEATURE_GREY_RELEASE_PRISONS"
echo AA - PUBLIC_PRIVATE_NOTES="$AA_BVLS_FEATURE_MASTER_PUBLIC_PRIVATE_NOTES"
echo DPS  - PUBLIC_PRIVATE_NOTES="$DPS_BVLS_PUBLIC_PRIVATE_NOTES_FEATURE_TOGGLE_ENABLED"