---
# Per environment values which override defaults in hmpps-book-a-video-link-api/values.yaml

generic-service:
  ingress:
    host: book-a-video-link-api.prison.service.justice.gov.uk

  env:
    API_BASE_URL_ACTIVITIES_APPOINTMENTS: "https://activities-api.prison.service.justice.gov.uk"
    API_BASE_URL_HMPPS_AUTH: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_LOCATIONS_INSIDE_PRISON: "https://locations-inside-prison-api.hmpps.service.justice.gov.uk"
    API_BASE_URL_MANAGE_USERS: "https://manage-users-api.hmpps.service.justice.gov.uk"
    API_BASE_URL_PRISON_API: "https://prison-api.prison.service.justice.gov.uk"
    API_BASE_URL_PRISONER_SEARCH: "https://prisoner-search.prison.service.justice.gov.uk"
    API_BASE_URL_WHEREABOUTS: "https://whereabouts-api.service.justice.gov.uk"
    API_BASE_URL_NOMIS_MAPPING: "https://nomis-sync-prisoner-mapping.hmpps.service.justice.gov.uk"
    BVLS_FRONTEND_URL: "https://book-a-video-link.prison.service.justice.gov.uk"

    postgresDatabaseRestore:
      enabled: false
      namespace_secrets:
        rds-postgresql-instance-output:
          DB_NAME: "database_name"
          DB_USER: "database_username"
          DB_PASS: "database_password"
          DB_HOST: "rds_instance_address"
        rds-postgresql-instance-output-preprod:
          DB_NAME_PREPROD: "database_name"
          DB_USER_PREPROD: "database_username"
          DB_PASS_PREPROD: "database_password"
          DB_HOST_PREPROD: "rds_instance_address"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-book-a-video-link-prod
  sqsOldestAlertQueueNames:
    - "hmpps-book-a-video-link-prod-hmpps_book_a_video_link_domain_queue"
  sqsNumberAlertQueueNames:
    - "hmpps-book-a-video-link-prod-hmpps_book_a_video_link_domain_dlq"
