---
# Per environment values which override defaults in hmpps-book-a-video-link-api/values.yaml

generic-service:
  ingress:
    host: hmpps-book-a-video-link-api.hmpps.service.justice.gov.uk

  env:
    API_BASE_URL_HMPPS_AUTH: "https://sign-in.hmpps.service.justice.gov.uk/auth"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: dps_alerts
