---
# Per environment values which override defaults in hmpps-book-a-video-link-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: book-a-video-link-api-dev.prison.service.justice.gov.uk

  env:
    SPRING_PROFILES_ACTIVE: dev
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_ACTIVITIES_APPOINTMENTS: "https://activities-api-dev.prison.service.justice.gov.uk"
    API_BASE_URL_HMPPS_AUTH: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_LOCATIONS_INSIDE_PRISON: "https://locations-inside-prison-api-dev.hmpps.service.justice.gov.uk"
    API_BASE_URL_MANAGE_USERS: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    API_BASE_URL_PRISON_API: "https://prison-api-dev.prison.service.justice.gov.uk"
    API_BASE_URL_PRISONER_SEARCH: "https://prisoner-search-dev.prison.service.justice.gov.uk"
    API_BASE_URL_NOMIS_MAPPING: "https://nomis-sync-prisoner-mapping-dev.hmpps.service.justice.gov.uk"
    BVLS_FRONTEND_URL: "https://book-a-video-link-dev.prison.service.justice.gov.uk"

  namespace_secrets:
    administration:
      ADMINISTRATION_EMAILS: "ADMINISTRATION_EMAILS"

  allowlist:
    groups:
      - internal
      - prisons
      - moj_cloud_platform
      - digital_staff_and_mojo

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: hmpps-book-a-video-link-dev
  sqsOldestAlertQueueNames:
    - "hmpps-book-a-video-link-dev-hmpps_book_a_video_link_domain_queue"
  sqsNumberAlertQueueNames:
    - "hmpps-book-a-video-link-dev-hmpps_book_a_video_link_domain_dlq"

cron:
  courtHearingLinkReminderJob: "0 11 * * 1-5"
  probationOfficerDetailsReminderJob: "0 11 * * 1-5"
